- set_fact:
    GO_VERSION: 1.9

- set_fact:
    url: "https://storage.googleapis.com/golang/go{{ GO_VERSION }}.linux-amd64.tar.gz"
  when: ansible_os_family == "Debian"

- name: Install from {{ url }}
  unarchive: src={{ url }} dest="{{ lookup('env','HOME') }}/usr/local" remote_src=yes
  when: ansible_os_family == "Debian"

- homebrew: name=go state=present
  when: ansible_os_family == "Darwin"

- file: state=link src=/usr/local/opt/go/libexec dest="{{ lookup('env','HOME') }}/usr/local/go"
  when: ansible_os_family == "Darwin"

- name: go get
  shell: go get {{ item }}
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/usr/local"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/golang/lint/golint
    - github.com/nsf/gocode
    - github.com/Masterminds/glide
    - github.com/rogpeppe/godef
