- name: set go version
  set_fact:
    GO_VERSION: "1.11"

- name: set go uri for Debian
  set_fact:
    url: "https://storage.googleapis.com/golang/go{{ GO_VERSION }}.linux-amd64.tar.gz"
  when: ansible_os_family == "Debian"

- name: install from go bin for Debian
  unarchive: src={{ url }} dest="{{ lookup('env','HOME') }}/usr/local" remote_src=yes
  when: ansible_os_family == "Debian"

- name: install from go bin for Darwin
  homebrew: name=go state=present
  when: ansible_os_family == "Darwin"

- name: set link go bin for Darwin
  file: state=link src=/usr/local/opt/go/libexec dest="{{ lookup('env','HOME') }}/usr/local/go"
  when: ansible_os_family == "Darwin"

- name: go get development tool
  shell: "{{ lookup('env','HOME') }}/usr/local/go/bin/go get {{ item }}"
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/usr/local"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/golang/lint/golint
    - github.com/nsf/gocode
    - github.com/Masterminds/glide
    - github.com/rogpeppe/godef
    - github.com/motemen/gobump/cmd/gobump
    - github.com/tcnksm/ghr
    - github.com/laher/goxc

- name: go get development tool
  shell: "{{ lookup('env','HOME') }}/usr/local/go/bin/go get {{ item }}"
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/usr/local"
  with_items:
    - github.com/ariarijp/crontoc
