- name: set go version
  set_fact:
    GO_VERSION: "1.11.2"

- name: set go uri for Debian
  set_fact:
    url: "https://dl.google.com/go/go{{ GO_VERSION }}.linux-amd64.tar.gz"
  when: ansible_os_family == "Debian"

- name: set go uri for Debian
  set_fact:
    url: "https://dl.google.com/go/go{{ GO_VERSION }}.darwin-amd64.tar.gz"
  when: ansible_os_family == "Darwin"

- name: install from go bin
  unarchive: src={{ url }} dest="{{ lookup('env','HOME') }}/usr/local" remote_src=yes

# - name: set link go bin for Darwin
#   file: state=link src=/usr/local/opt/go/libexec dest="{{ lookup('env','HOME') }}/usr/local/go"
#   when: ansible_os_family == "Darwin"

- name: go get development tool
  shell: "{{ lookup('env','HOME') }}/usr/local/go/bin/go get {{ item }}"
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/usr/local"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/pwaller/goimports-update-ignore
    - github.com/monochromegane/dragon-imports/cmd/dragon-imports
    - github.com/golang/lint/golint
    - github.com/mdempsky/gocode
    - github.com/Masterminds/glide
    - github.com/rogpeppe/godef
    - github.com/motemen/gobump/cmd/gobump
    - github.com/tcnksm/ghr
    - github.com/laher/goxc
    - github.com/izumin5210/gex/cmd/gex

- name: go get development tool
  shell: "{{ lookup('env','HOME') }}/usr/local/go/bin/go get {{ item }}"
  environment:
    GOPATH: "{{ lookup('env','HOME') }}/usr/local"
  with_items:
    - github.com/ariarijp/crontoc
