# - name: Change /usr/local owner to "{{ ansible_user_id }}"
#   become: true
#   become_method: sudo
#   file:
#     dest: /usr/local
#     owner: "{{ ansible_user_id }}"
#     group: admin
#     recurse: yes

- name: brew taps
  homebrew_tap: name={{ item }}
  with_items:
    - tidwall/jd  ## for jd

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- homebrew:
    state: present
    name: "{{ item }}"
    install_options: ""
  with_items:
    - coreutils
    - jq
    - wget
    - shellcheck
    - peco
    - packer
    - ag
    - jd
    - zsh-completions
    - percona-toolkit # pt-query-digest

- homebrew_cask:
    state: present
    name: "{{ item }}"
  with_items:
    - docker
    - sequel-pro
