- debug: var=ansible_os_family

- file: path="{{ lookup('env','HOME') }}/usr/local/bin" state=directory

- include: "{{ ansible_os_family }}.yml"

- name: Clone scripts
  git:
    repo: git@github.com:{{ my_github_account }}/scripts.git
    dest: "{{ lookup('env','HOME') }}/src/github.com/{{ my_github_account }}/scripts"
    version: master
