- name: Clone dotfiles
  git:
    repo: git@github.com:{{ my_github_account }}/dotfiles.git
    dest: "{{ lookup('env','HOME') }}/src/github.com/{{ my_github_account }}/dotfiles"
    version: master

- name: Make dot directories
  file:
    state: directory
    path: "{{ lookup('env','HOME') }}/{{ item }}"
  with_items:
    - .config
    - .bak.emacs
    - .emacs.d
    - .jupyter

- name: Create link to dotfile repo
  file:
    state: link
    path: "{{ lookup('env','HOME') }}/{{ item }}"
    src: "{{ lookup('env','HOME') }}/src/github.com/{{ my_github_account }}/dotfiles/{{ item }}"
  with_items:
    - ".share"
    - ".config/flake8"
    - ".config/pip"
    - ".gitconfig"
    - ".zshrc"
    - ".zsh.d"
    - ".ssh/conf.d"
    - ".snippets"
    - ".emacs.d/init.el"
    - ".screenrc"
    - ".dircolors"
    - ".my.cnf"
    - ".jupyter/jupyter_notebook_config.py"

- name: Make dir for zsh setting
  file:
    state: directory
    path: "{{ lookup('env','HOME') }}/usr/local/zsh/"

- name: Clone zsh-completions
  git:
    repo: git@github.com:zsh-users/zsh-completions.git
    dest: "{{ lookup('env','HOME') }}/usr/local/zsh/zsh-completions"
    version: master
