- name: Clone dotfiles
  git:
    repo: git@github.com:{{ my_github_account }}/dotfiles.git
    dest: ~/dotfiles
    version: master

- file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.config"

- file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.bak.emacs"

- file:
    state: link
    path: "{{ lookup('env','HOME') }}/{{ item }}"
    src: "{{ lookup('env','HOME') }}/dotfiles/{{ item }}"
  with_items:
    - ".share"
    - ".config/flake8"
    - ".config/pip"
    - ".gitconfig"
    - ".zshrc"
    - ".zsh.d"
    - ".ssh/conf.d"
    - ".snippets"
