- name: Clone dotfiles
  git:
    repo: git@github.com:{{ my_github_account }}/dotfiles.git
    dest: "{{ lookup('env','HOME') }}/src/github.com/{{ my_github_account }}/dotfiles"
    version: master

- file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.config"

- file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.bak.emacs"

- file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.emacs.d"

- file:
    state: link
    path: "{{ lookup('env','HOME') }}/{{ item }}"
    src: "{{ lookup('env','HOME') }}/src/github.com/{{ my_github_account }}/dotfiles/{{ item }}"
  with_items:
    - ".share"
    - ".config/flake8"
    - ".config/pip"
    - ".gitconfig"
    - ".zshrc"
    - ".zsh.d"
    - ".ssh/conf.d"
    - ".snippets"
    - ".emacs.d/init.el"
    - ".screenrc"
    - ".dircolors"


- name: Clone zsh-completions
  git:
    repo: git@github.com:zsh-users/zsh-completions.git
    dest: "{{ lookup('env','HOME') }}/src/github.com/zsh-users/zsh-completions"
    version: master
