---
- name: Clone ndenv
  git:
    repo: git@github.com:riywo/ndenv.git
    dest: "{{ lookup('env','HOME') }}/.ndenv"
    version: master

- name: Clone node-build
  git:
    repo: git@github.com:riywo/node-build.git
    dest: "{{ lookup('env','HOME') }}/.ndenv/plugins/node-build"
    version: master
