---
- name: Remove ndenv
  file:
    state: absent
    path: "{{ lookup('env','HOME') }}/.ndenv"

- name: Clone nodenv
  git:
    repo: git@github.com:nodenv/nodenv.git
    dest: "{{ lookup('env','HOME') }}/.nodenv"
    version: master

- name: Clone node-build
  git:
    repo: git@github.com:nodenv/node-build.git
    dest: "{{ lookup('env','HOME') }}/.nodenv/plugins/node-build"
    version: master

- name: Clone nodenv-yarn-install
  git:
    repo: git@github.com:pine/nodenv-yarn-install.git
    dest: "{{ lookup('env','HOME') }}/.nodenv/plugins/nodenv-yarn-install"
    version: master
