- name: Clone rbenv
  git:
    repo: git@github.com:rbenv/rbenv.git
    dest: ~/.rbenv
    version: master

- name: Clone ruby-build
  git:
    repo: git@github.com:rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    version: master
